- name: Ensure common packages are installed
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - git
    - build-essential
    - wget
    - curl
    - make
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3